# Generated by Django 4.0.1 on 2022-07-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название страны')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.TextField(default='AAA', max_length=3, verbose_name='Аэропорт вылета (IATA)')),
                ('description', models.TextField(blank=True, max_length=280, verbose_name='Описание тура')),
                ('promoted', models.BooleanField(default=False, verbose_name='Продвижение в блоке с рекламой')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction', models.IntegerField(verbose_name='Размер скидки')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.tour')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название города')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.country')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=3, verbose_name='IATA код')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.city')),
            ],
        ),
    ]
