# Generated by Django 4.0.1 on 2022-07-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='arrival_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_date',
            field=models.DateTimeField(null=True),
        ),
    ]
