# Generated by Django 4.0.1 on 2022-07-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_tour_arrival_date_tour_departure_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название отеля')),
                ('stars', models.IntegerField(choices=[(0, 'Без звёзд'), (1, 'Одна звезда'), (2, 'Две звезды'), (3, 'Три звезды'), (4, 'Четыре звезды'), (5, 'Пять звезд')], default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.city')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.hotel'),
        ),
    ]
