# Generated by Django 4.0.1 on 2022-07-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_tour_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='count_travelers',
            field=models.SmallIntegerField(default=2),
        ),
    ]
