# Generated by Django 4.0.1 on 2022-07-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_tour_count_travelers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.TextField(max_length=3, unique=True, verbose_name='IATA код'),
        ),
    ]
