# Generated by Django 4.0.1 on 2022-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_airport_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='Цена тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='arrival_date',
            field=models.DateTimeField(null=True, verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='count_travelers',
            field=models.SmallIntegerField(default=2, verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='departure_date',
            field=models.DateTimeField(null=True, verbose_name='Дата оправления'),
        ),
    ]
