# Generated by Django 4.0.1 on 2022-07-06 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_tour_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.discount'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='images',
            field=models.ImageField(null=True, upload_to='hotels/'),
        ),
    ]
