# Generated by Django 4.0.1 on 2022-07-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_remove_discount_tour_tour_discount_alter_tour_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.discount'),
        ),
    ]
