# Generated by Django 4.0.1 on 2022-07-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_alter_tour_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='images_2',
            field=models.ImageField(null=True, upload_to='hotels/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='images_3',
            field=models.ImageField(null=True, upload_to='hotels/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='images_4',
            field=models.ImageField(null=True, upload_to='hotels/'),
        ),
    ]
