# Generated by Django 4.0.1 on 2022-07-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_tour_images_2_tour_images_3_tour_images_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='contact_phone',
            field=models.TextField(blank=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='tour',
            name='site_url',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.tour')),
            ],
        ),
    ]
